[build]
  command   = "cd mvp-app && npm run build"
  publish   = "mvp-app/out"

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL       = "\${env:NEXT_PUBLIC_SUPABASE_URL}"
  NEXT_PUBLIC_SUPABASE_ANON_KEY  = "\${env:NEXT_PUBLIC_SUPABASE_ANON_KEY}"
  OPENAI_API_KEY                 = "\${env:OPENAI_API_KEY}"
